apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  type: ClusterIP
  selector:
    app: my-db-data
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: vprodb-int-frontend
      port: 3306
      targetPort: vprodbport
      protocol: TCP
