apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rmq01
  labels:
    app: my-rmq01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-rmq01
  template:
    metadata:
      labels:
        app: my-rmq01
    spec:
      containers:
        - name: vpromq01
          image: rabbitmq
          ports:
            - name: vpromqport
              containerPort: 15672
          env: 
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
            - name:  RABBITMQ_DEFAULT_USER
              value: "guest"