apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  type: ClusterIP
  selector:
    app: my-rmq01
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: vpromq-int-frontend
      port: 15672
      targetPort: vpromqport
      protocol: TCP
