apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  type: LoadBalancer
  selector:
    app: vproapp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: vproapp-service-port
      port: 80
      targetPort: vproappport
      protocol: TCP
